---
project:
  name: jailang
  owner: pixeldroid
  repo: https://github.com/pixeldroid/jailang
  version: '3'
collections:
  overview:
    output: true
    permalink: "/:collection/:path/"
    title: Overview
    tab-order: 1
  reference:
    output: true
    permalink: "/:collection/:path/"
    title: Reference
    tab-order: 2
  modules:
    output: true
    permalink: "/:collection/:path/"
    title: Modules
    tab-order: 3
  examples:
    output: true
    permalink: "/:collection/:path/"
    title: Examples
    tab-order: 4
code_indent: "  "
highlighter: rouge
include:
- "#*.md"
- "_*.md" # built-in types, fields, and procedures start with underscore
kramdown:
  footnote_backlink: '⮌'
permalink: pretty
sass:
  style: compressed
plugins:
- jemoji
- jekyll-remote-theme
#theme: programming-pages
remote_theme: pixeldroid/programming-pages
