---
project:
  name: jailang
  owner: pixeldroid
  repo: https://github.com/pixeldroid/jailang
  version: 2
collections:
  overview:
    output: true
    permalink: "/:collection/:path/"
    title: Overview
    tab-order: 1
  features:
    output: true
    permalink: "/:collection/:path/"
    title: Features
    tab-order: 2
  stdlib:
    output: true
    permalink: "/:collection/:path/"
    title: StdLib
    tab-order: 3
  examples:
    output: true
    permalink: "/:collection/:path/"
    title: Examples
    tab-order: 4
code_indent: "  "
highlighter: rouge
include:
- "#*.md"
kramdown:
  footnote_backlink: '⮌'
permalink: pretty
sass:
  style: compressed
plugins:
- jemoji
- jekyll-remote-theme
remote_theme: pixeldroid/programming-pages
